name: release plugin

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:
  
jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 8
        run_install: true

    - name: Build
      run: pnpm build
    
    - name: Create release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: |
              main.js
              manifest.json
              styles.css
